### ISSUE TITLE
Random crashes from wayland on committing to deleted windows

### ISSUE THREAD

**Issue by vaxerski** [vaxerski/Hyprland#7]
Rare crashes when closing/opening (opening not sure) a window from wl.

Coredump:
```
#0  0x00007f4878ad9f27 wl_list_remove (libwayland-server.so.0 + 0xdf27)
#1  0x00007f4878c31d65 surface_commit_state (libwlroots.so.11 + 0x67d65)
#2  0x00007f4877e65d4a n/a (libffi.so.8 + 0x6d4a)
#3  0x00007f4877e65267 n/a (libffi.so.8 + 0x6267)
```

**Comment by vaxerski** [comment]
possibly fixed with e72fc4fca2089fcf5d364d81cac683ba12a62db8, but I am not sure

**Comment by vaxerski** [comment]
Coredump with newest commit:
```
#0  0x00007f5fdea30edb in wl_list_remove () from /usr/lib/libwayland-server.so.0
[Current thread is 1 (Thread 0x7f5fdd375340 (LWP 60541))]
(gdb) bt -full
#0  0x00007f5fdea30edb in wl_list_remove () at /usr/lib/libwayland-server.so.0
#1  0x00007f5fdeb8bd65 in surface_commit_state (surface=0x563d40430480, next=0x563d40430608)
    at ../wlroots-git/types/wlr_compositor.c:444
        invalid_buffer = <optimized out>
        subsurface = 0x563d4000c4e0
        __PRETTY_FUNCTION__ = "surface_commit_state"
#2  0x00007f5fdddc1d4a in  () at /usr/lib/libffi.so.8
#3  0x00007f5fdddc1267 in  () at /usr/lib/libffi.so.8
#4  0x00007f5fdea2faf2 in  () at /usr/lib/libwayland-server.so.0
#5  0x00007f5fdea33e14 in  () at /usr/lib/libwayland-server.so.0
#6  0x00007f5fdea3284a in wl_event_loop_dispatch () at /usr/lib/libwayland-server.so.0
#7  0x00007f5fdea33047 in wl_display_run () at /usr/lib/libwayland-server.so.0
#8  0x0000563d3da6b345 in main ()
```

**Comment by vaxerski** [comment]
fucking typos
